# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "templatedemo",
  srcs = ["templatedemo.cc"],
  copts = [],
  deps = [],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "traitsdemo",
  srcs = ["traitsdemo.cc"],
  copts = [],
  deps = [],
)